In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("../data/survey_results_public.csv")

# Show initial structure
print(df.shape)
df.head()

(89184, 84)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0

In [2]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('../data/survey_results_public.csv')

# Display original shape
print(f"Original shape: {df.shape}")

# Select relevant columns
df = df[[
    'Country',
    'EdLevel',
    'YearsCodePro',
    'Employment',
    'ConvertedCompYearly'
]]

# Remove rows with missing target variable (salary)
df = df[df['ConvertedCompYearly'].notnull()]

# Drop rows with too many missing values
df.dropna(inplace=True)

# Clean YearsCodePro
def clean_experience(x):
    if x == 'More than 50 years':
        return 50
    elif x == 'Less than 1 year':
        return 0.5
    else:
        try:
            return float(x)
        except:
            return np.nan

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

# Drop any remaining NaNs after conversion
df.dropna(inplace=True)

# Simplify Education Level
def clean_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    elif 'Master’s degree' in x:
        return 'Master’s degree'
    elif 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post Grad'
    else:
        return 'Less than Bachelor’s'

df['EdLevel'] = df['EdLevel'].apply(clean_education)

# Simplify Employment Type
def clean_employment(x):
    if 'Employed full-time' in x:
        return 'Full-time'
    elif 'Employed part-time' in x:
        return 'Part-time'
    else:
        return 'Other'

df['Employment'] = df['Employment'].apply(clean_employment)

# Filter out outliers (keep only salaries under 300,000 USD)
df = df[df['ConvertedCompYearly'] < 300000]

# Optional: Filter countries with fewer responses
country_counts = df['Country'].value_counts()
country_threshold = 400  # countries with less than 400 responses will be grouped as "Other"
df['Country'] = df['Country'].apply(lambda x: x if country_counts[x] >= country_threshold else 'Other')

# One-hot encoding for categorical variables
df = pd.get_dummies(df, columns=['Country', 'EdLevel', 'Employment'], drop_first=True)

# Final check
print(f"Cleaned shape: {df.shape}")
df.head()

Original shape: (89184, 84)
Cleaned shape: (46643, 31)

,YearsCodePro,ConvertedCompYearly,Country_Austria,Country_Belgium,Country_Brazil,Country_Canada,Country_Czech Republic,Country_Denmark,Country_Finland,Country_France,...,Country_Russian Federation,Country_Spain,Country_Sweden,Country_Switzerland,Country_Ukraine,Country_United Kingdom of Great Britain and Northern Ireland,Country_United States of America,EdLevel_Less than Bachelor’s,EdLevel_Master’s degree,EdLevel_Post Grad
1,9.0,285000.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,23.0,250000.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,7.0,156000.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,4.0,23456.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,21.0,96828.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False

In [4]:
# Save the cleaned dataset
df.to_csv('../processed/cleaned_data.csv', index=False)
print("Cleaned dataset saved to ../processed/cleaned_data.csv")

Cleaned dataset saved to ../processed/cleaned_data.csv